### PR TITLE
Fix vulnerabilities of dev dependencies

### PR DESCRIPTION
**Pull request by stefan-prokop-cz**

### CODE REVIEW

**Comment by smoliji** [comment]
Just being curious, why the only change is in pacakge-lock.json? :thinking:

If only installing the dependencies within the bounds makes this ok, I'd rather lock them in package.json. Othwerwise this can break again anytime by it self! :scream:

**Comment by stefan-prokop-cz** [comment]
These packages was not inside our `package.json` but its dependencies of our dependencies and its reason why package-lock changed right?

I added these packages into our `package.json` file

**Comment by smoliji** [comment]
> These packages was not inside our `package.json` but its dependencies of our dependencies and its reason why package-lock changed right?
> 
> I added these packages into our `package.json` file

Cool you moved types to devDependencies.

The rest though, cannot we update the root dependencies directly? I would add deps-of-deps to project deps iff the root dep doesnt have a newer version - the root deps should fix this. Does that make sense?

**Comment by grissius** [comment]
@smoliji No, if we don't use them we should not have them in our own dependencies. Fixing the transitive dependencies should be done in lock, as @stefan-prokop-cz did.

**Comment by grissius** [comment]
@stefan-prokop-cz Also please use [GItmoji](https://github.com/AckeeCZ/styleguide/blob/master/git/guides/commit-message.md) next time :pray:

**Comment by stefan-prokop-cz** [comment]
> @stefan-prokop-cz Also please use [GItmoji](https://github.com/AckeeCZ/styleguide/blob/master/git/guides/commit-message.md) next time

sorry, I saw it after my last commit :disappointed:

**Pull request merged**
